@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjNhNjVmYi03NDliLTRkYTgtYTkzNC01OWFmYjkxZTRlNWIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiYTBhZTI1ZTEtY2M0Ni00OTFmLTkzY2ItODBlYTAyOGM0ZjgxIiwiZXhwIjoxNzE3NjA2MTI2LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.6AP5Ir-C8Fp7v7IWymZFvfhDfED1vWkkvMchjxy7FRk

POST {{host}}/borrowings
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": "3b3a65fb-749b-4da8-a934-59afb91e4e5b",
    "bookId": "2",
    "maxDaysUntilReturn": 1
}