@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjNhNjVmYi03NDliLTRkYTgtYTkzNC01OWFmYjkxZTRlNWIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiYWEzNjA3ZDktNzMwZS00ODg5LTgyY2YtODgxZjNiMjAyNWRlIiwiZXhwIjoxNzE3NTIyNzA5LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.qCDUsU_M6jat6m4IOjldzs0X1OO0Hip55K_wUXpTnOE

@id = 1

DELETE {{host}}/books/{{id}}
Authorization: Bearer {{token}}