@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjNhNjVmYi03NDliLTRkYTgtYTkzNC01OWFmYjkxZTRlNWIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiZGIyOTk2ODItNzJjMC00NjNiLWEyMDQtNWNjMTYyNGI0ZjIxIiwiZXhwIjoxNzE3NjAxMjU2LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.bhqsBfzPTljktz3XYjxyIohyK3MYlOcNOhIj0a6z7lY

@id = 2

GET {{host}}/books/{{id}}
Authorization: Bearer {{token}}
