@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2Q0Y2M2MS03ZmM3LTQxYTYtOTQ0MS00NTU3NmVhMTJiZmIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiNzI5Y2M2YzMtNDg2OS00MDk2LWJhOTAtNThhOTAxOTZkNGVjIiwiZXhwIjoxNzE3NjcxMjk4LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.9MqNpsUfzXt-7paIEKNDj4HYeGJhVhD_lhdU5tXQ04o

POST {{host}}/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Alica v krajine zazrakov",
    "description": "Zaujimava poviedka",
    "author": "Lewis Carroll",
    "isbn": "123-456-789-X",
    "totalCopies": 26
}

###
POST {{host}}/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Móricako na ceste do sveta Simpanzov",
    "description": "",
    "author": "Devin Black",
    "isbn": "123-456-789-2",
    "totalCopies": 2
}