@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2Q0Y2M2MS03ZmM3LTQxYTYtOTQ0MS00NTU3NmVhMTJiZmIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiNzI5Y2M2YzMtNDg2OS00MDk2LWJhOTAtNThhOTAxOTZkNGVjIiwiZXhwIjoxNzE3NjcxMjk4LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.9MqNpsUfzXt-7paIEKNDj4HYeGJhVhD_lhdU5tXQ04o

@id = 5

GET {{host}}/books/{{id}}
Authorization: Bearer {{token}}
