@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjNhNjVmYi03NDliLTRkYTgtYTkzNC01OWFmYjkxZTRlNWIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiZDg2YzY3ZmItOWY1Ny00YmI0LWFiNjAtM2JiYWI4MGZkY2JlIiwiZXhwIjoxNzE3NjA3MDg4LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.RaQmCam3jBDcTV-ENuPRxJo4IXrnde6iNRgYQmjRAuE

@id = 3

GET {{host}}/books/{{id}}
Authorization: Bearer {{token}}
