@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2Q0Y2M2MS03ZmM3LTQxYTYtOTQ0MS00NTU3NmVhMTJiZmIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiNzI5Y2M2YzMtNDg2OS00MDk2LWJhOTAtNThhOTAxOTZkNGVjIiwiZXhwIjoxNzE3NjcxMjk4LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.9MqNpsUfzXt-7paIEKNDj4HYeGJhVhD_lhdU5tXQ04o

@id1 = 5
PUT {{host}}/books/{{id1}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id1}},
    "title": "Alica v krajine zazrakov",
    "description": "Zaujimava poviedka",
    "author": "James Carrol",
    "isbn": "123-456-789-X",
    "totalCopies": 26
}

###
@id2 = 2
PUT {{host}}/books/{{id2}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id2}},
    "title": "Móricko na ceste do sveta Simpanzov",
    "description": "",
    "author": "Devin Black",
    "isbn": "123-456-789-2",
    "totalCopies": 2
}