@host = http://localhost:5066
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjNhNjVmYi03NDliLTRkYTgtYTkzNC01OWFmYjkxZTRlNWIiLCJnaXZlbl9uYW1lIjoiTWF0dXMiLCJmYW1pbHlfbmFtZSI6IlphcHJhem55IiwianRpIjoiZGIyOTk2ODItNzJjMC00NjNiLWEyMDQtNWNjMTYyNGI0ZjIxIiwiZXhwIjoxNzE3NjAxMjU2LCJpc3MiOiJMaWJyYXJ5TWFuYWdlciIsImF1ZCI6IkxpYnJhcnlNYW5hZ2VyIn0.bhqsBfzPTljktz3XYjxyIohyK3MYlOcNOhIj0a6z7lY

@id1 = 1
PUT {{host}}/books/{{id1}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id1}},
    "title": "Alica v krajine zazrakov",
    "description": "Zaujimava poviedka",
    "author": "James Carrol",
    "isbn": "123-456-789-X",
    "totalCopies": 26
}

###
@id2 = 2
PUT {{host}}/books/{{id2}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id2}},
    "title": "Móricko na ceste do sveta Simpanzov",
    "description": "",
    "author": "Devin Black",
    "isbn": "123-456-789-2",
    "totalCopies": 2
}